apiVersion: v1
kind: ServiceAccount
metadata:
  name: test1
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::127710927797:role/oidc-test
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test2
---
apiVersion: v1
kind: Pod
metadata:
  name: test1
spec:
  ServiceAccountName: test1
  containers:
    - name: debug
      image: rkalluru/loaded:centos8
---
apiVersion: v1
kind: Pod
metadata:
  name: test2
spec:
  ServiceAccountName: test2
  containers:
    - name: debug
      image: rkalluru/loaded:centos8
