apiVersion: v1
kind: ServiceAccount
metadata:
  name: test1
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test2
---
apiVersion: v1
kind: Pod
metadata:
  name: test1
spec:
  containers:
    - name: debug
      image: rkalluru/loaded:centos8
---
apiVersion: v1
kind: Pod
metadata:
  name: test2
spec:
  containers:
    - name: debug
      image: rkalluru/loaded:centos8
